version: '3.8'

services:
  # Base de datos principal (MongoDB)
  mongo:
    image: mongo:latest
    container_name: axio_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- NUEVO: Visor Web para la Base de Datos ---
  mongo-express:
    image: mongo-express
    container_name: axio_admin
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo
  # ----------------------------------------------

  # Base de datos cach√© (Redis)
  redis:
    image: redis:alpine
    container_name: axio_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data: